artifactId: $name;format="lower,package"$
artifactVersion: "0.0.1"
groupId: $organisation;format="lower,package"$
packageName: $pckg;format="lower,package"$
modelPackage: $pckg;format="lower,package"$.model
apiPackage: $pckg;format="lower,package"$.api
gitRepoId: $organisation$
gitUserId: $github_username;format="norm"$