name: Two-Phase Build and Test

on:
  push:
    branches:
      - "*" 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
                ${{ runner.os }}-sbt-

      - name: Set up GitHub Packages credentials
        run: echo -e "realm=GitHub Package Registry\nhost=maven.pkg.github.com\nuser=${{ github.actor }}\npassword=${{ secrets.GH_TOKEN }}" > ~/.sbt/.credentials
            
      - name: Generate our test project
        run: |
          sbt new file://$GITHUB_WORKSPACE --name=localtest
          cd localtest
          sbt test
